capacities = "./data/toulon/loc_capacities.txt"
distance_matrix = "./data/toulon/dist_matrix.txt"
output = "./results/test_toulon"
weights = "./data/toulon/cust_weights.txt"
verbose = true
threads = 4
mode = 2
p = 5
seed = 1
time = 3600
time_cplex = 3600
toleranceCpt = 0
k = 1
percentage = 80
service = "null"
method = "TB_PMP"
method_rssv_sp = "TB_PMP"
method_rssv_fp = "TB_PMP"