verbose = false
p = 5
capacities = "./data/toulon/loc_capacities.txt"
distance_matrix = "./data/toulon/dist_matrix.txt"
output = ""
weights = "./data/toulon/cust_weights.txt"
threads = 4
mode = 3
seed = 1
time = 7200