capacities = "./data/toulon/loc_capacities.txt"
distance_matrix = "./data/toulon/dist_matrix.txt"
output = "./results/test_toulon"
weights = "./data/toulon/cust_weights.txt"
coverages= ""
coverages_n2= ""
cover = "null"
cover_mode = false
cover_mode_n2 = false
verbose = false
threads = 4
mode = 2
p = 5
seed = 0
IsWeighted_ObjFunc=1
time = 3600
time_cplex = 3600
toleranceCpt = 0
k = 1
cust_max_id=0
loc_max_id=0
percentage = 80
service = "null"
subarea = "null"
subarea_n2 = "null"
method = "TB_PMP"
method_rssv_sp = "TB_PMP"
method_rssv_fp = "TB_PMP"
method_post_opt = "null"
size_subproblems_rssv=800
time_subprob_rssv=0
max_ite_subprob_rssv = 0
add_threshold_distance_rssv = false
bw_multiplier=1