verbose = true
p = 50
capacities = "./data/paca_v3/capacities_mat.txt"
distance_matrix = "./data/paca_v3/dist_matrix.txt"
output = "./results/test_paca_tbpercentage.txt"
weights = "./data/paca_v3/cust_weights.txt"
threads = 12
mode = 5
seed = 48456
time = 25000
toleranceCpt = 10
k = 50000
percentage = 80
