verbose = true
p = 5
capacities = "./data/toulon/loc_capacities.txt"
distance_matrix = "./data/toulon/dist_matrix.txt"
output = "./results/test_toulon"
weights = "./data/toulon/cust_weights.txt"
threads = 4
mode = 3
seed = 48456
time = 3600
toleranceCpt = 10
k = 1
percentage = 80