verbose = true
p = 42
capacities = "./data/filterData_PACA_may23/loc_capacities_cap_mat.txt"
distance_matrix = "./data/filterData_PACA_may23/dist_matrix_minutes.txt"
output = "./results/test_paca_mat"
output_loc = "./results/outputLOC_paca_mat"
output_vars = "./results/outputVARS_paca_mat"
output_table = "./results/outputTABLE_paca_mat"
weights = "./data/filterData_PACA_may23/cust_weights.txt"
threads = 4
mode = 7
seed = 48456
time = 3600
time_cplex = 3600
toleranceCpt = 10
k = 1
percentage = 80
service = "mat"
method = "TB_PMP"
method_rssv_sp = "TB_PMP"
method_rssv_fp = "TB_PMP"