verbose = true
p = 5
capacities = "./data/toulon/loc_capacities.txt"
distance_matrix = "./data/toulon/dist_matrix.txt"
output = "./results/test_toulon"
output_loc = "./results/outputLOC_toulon"
output_vars = "./results/outputVARS_toulon"
output_table = "./results/outputTABLE_toulon"
weights = "./data/toulon/cust_weights.txt"
threads = 4
mode = 3
seed = 48456
time = 3600
time_cplex = 3600
toleranceCpt = 0
k = 1
percentage = 80
service = "null"
method = "TB_PMP"
method_rssv_sp = "TB_PMP"
method_rssv_fp = "TB_PMP"