verbose = true
p = 60
capacities = "./data/filterData_PACA_may23/loc_capacities_cap_urgenc.txt"
distance_matrix = "./data/filterData_PACA_may23/dist_matrix_minutes.txt"
output = "./results/test_paca_urgenc"
output_loc = "./results/outputLOC_paca_urgenc"
output_vars = "./results/outputVARS_paca_urgenc"
output_table = "./results/outputTABLE_paca_urgenc"
weights = "./data/filterData_PACA_may23/cust_weights.txt"
threads = 4
mode = 7
seed = 48456
time = 3600
toleranceCpt = 10
k = 1
percentage = 80
service = "urgenc"