verbose = true
p = 681
capacities = "./data/filterData_PACA_may23/loc_capacities_cap_poste.txt"
distance_matrix = "./data/filterData_PACA_may23/dist_matrix_minutes.txt"
output = "./results/test_paca_poste"
output_loc = "./results/outputLOC_paca_poste"
output_vars = "./results/outputVARS_paca_poste"
output_table = "./results/outputTABLE_paca_poste"
weights = "./data/filterData_PACA_may23/cust_weights.txt"
threads = 4
mode = 7
seed = 48456
time = 30
toleranceCpt = 10
k = 1
percentage = 80
